#!/bin/bash
#sudo -u postgres psql -c "DROP database prxdbs"
sudo -u postgres psql -c "CREATE ROLE r_processing_secured_ro"
sudo -u postgres psql -c "CREATE ROLE r_processing_secured_rw"
sudo -u postgres psql -c "CREATE ROLE r_processing_common_rw"
sudo -u postgres psql -c "CREATE ROLE g_all_tables_rw"
sudo -u postgres psql -c "CREATE ROLE g_all_tables_ro"
sudo -u postgres psql -c "CREATE ROLE u_processing"
sudo -u postgres psql -c "CREATE ROLE u_portal"
sudo -u postgres psql -c "CREATE ROLE r_portal_common_rw"
sudo -u postgres psql -c "CREATE ROLE g_client_license_types_tables_ro"
sudo -u postgres psql -c "CREATE ROLE u_master"
sudo -u postgres psql -c "CREATE ROLE g_machine_types_tables_rw"
sudo -u postgres psql -c "CREATE ROLE g_machine_types_tables_ro"
sudo -u postgres psql -c "CREATE ROLE g_token_tables_rw"
sudo -u postgres psql -c "CREATE ROLE r_master_secured_rw"
sudo -u postgres psql -c "CREATE ROLE r_master_secured_ro"
sudo -u postgres psql -c "CREATE ROLE g_client_tables_ro"
sudo -u postgres psql -c "CREATE ROLE r_master_common_rw"
sudo -u postgres psql -c "CREATE ROLE g_client_tables_rw"
sudo -u postgres psql -c "CREATE ROLE g_machines_tables_rw"
sudo -u postgres psql -c "CREATE ROLE g_machines_tables_ro"
sudo -u postgres psql -c "CREATE USER prxserver IN ROLE g_token_tables_rw, g_client_tables_ro, r_processing_common_rw, u_processing ENCRYPTED PASSWORD 'prxserver_102938'"
sudo -u postgres psql -c "CREATE database prxdbs"
sudo -u postgres psql -d prxdbs -f ../db/ddl/prxdbs.sql
